# Configuration for git-changelog (https://github.com/aldrin/git-changelog)
conventions:
  categories:
    - {tag: "break", title: "Breaking Change"}
    - {tag: "feature", title: "Feature"}
    - {tag: "improve", title: "Improvement"}
    - {tag: "fix", title: "Fix"}
  scopes:
    - {tag: "", title: "General"}
    - {tag: "win", title: "Windows"}
    - {tag: "mac", title: "macOS"}
output:
  post_processors:
    - {lookup: "GH-(?P<id>\\d+)", replace: "[GH-$id](https://github.com/jorgenpt/bichrome/issues/$id)"}
